# Fellowships
- service: Ad Hoc Reviewer
  organization1: Water Resources Research
  year1: 2020, 2021
  organization2: Physical Review Fluids
  year2: 2021
  organization3: Hydrogeology Journal
  year3: 2021
  organization4: International Journal of Greenhouse Gas Control
  year4: 2017
  organization5: Stochastic Environmental Research and Risk Assessment
  year5: 2010
  # summary: $60,000

- service: Training Seminar Speaker
  organization1: Fourth Midwest OpenFOAM User Group Meeting
  year1: 2019
  summary: Delivered a lecture with interactive components designed for training engineers and researchers on how to use Lagrangian solvers in OpenFOAM for particulate flows

