# Fellowships
- service: Ad Hoc Reviewer
  organization4: Journal of Fluid Mechanics
  year1: 2021
  organization7: Water Resources Research
  year2: 2020, 2021
  organization5: Physical Review Fluids
  year3: 2021
  organization1: Geophysical Research Letters 
  year7: 2021
  organization2: Hydrogeology Journal
  year4: 2021
  organization3: International Journal of Greenhouse Gas Control
  year5: 2017
  organization6: Stochastic Environmental Research and Risk Assessment
  year6: 2010

- service: Training Seminar Speaker
  organization1: Fourth Midwest OpenFOAM User Group Meeting
  year1: 2019
  summary: Delivered a lecture with interactive components designed for training engineers and researchers on how to use Lagrangian solvers in OpenFOAM for particulate flows

